### ISSUE TITLE
How to use the bundler and install a gem?

### ISSUE THREAD

**Issue by Whirlwind** [johnfairh/RubyGateway#21]
I want to use the bundler to manage all gems, but I could not find the correct way.

First, If I have a bundler gem  in the macos, how to use the bundler and gemfile?

Then, If there is not a bundler gem, I want to install a gem, How to run the command `gem install bundler`? It is a shell script, not a ruby script.  Must I use the NSTask to invoke the bash command?

**Comment by johnfairh** [comment]
This framework is about using Ruby code from Swift programs.

I'm not sure how it can help with your questions.

See [Process](https://developer.apple.com/documentation/foundation/process) in Foundation to run child processes from Swift.
