### ISSUE TITLE
How to require non-mainBundle ruby files

### ISSUE THREAD

**Issue by xareelee** [johnfairh/RubyGateway#29]
I could load a ruby file which is in the main bundle:

```swift
let url = Bundle.main.url(forResource: "file_name", withExtension: "rb")

do {
  if let path = url?.path {
    try Ruby.require(filename: path)
  }
} catch {
  print("error: \(error)")
}
```

but it can't load an existing ruby file which is already downloaded by the user. For example:

```swift
let path = "/tmp/hello.rb"
do {
  try Ruby.require(filename: path)
} catch {
  print("error: \(error)")
}
// error: Ruby exception: LoadError: cannot load such file -- /tmp/hello.rb
```

How to require a local ruby file and a ruby gem using RubyGateway?

**Comment by johnfairh** [comment]
You have as much information as I do: that is the exception reported by Ruby.

You haven't said what operating system you're working on.  Could it be that you are running into some kind of Apple sandbox issue that prevents you from accessing /tmp ?

**Comment by xareelee** [comment]
You're right. I didn't aware that. After finding and closing the "App Sandbox", it can run a local ruby file now.

Is it possible to load a ruby gem with RubyGateway? It failed to simply load the name:

```swift
try? Ruby.require(filename: "a_installed_ruby_gem")
```

**Comment by johnfairh** [comment]
Great.

Yes, Gems work.  From your other issue though, the version of Ruby with which you are using RubyGateway may not have the gems installed.

Check the load path (directories searched for gems) with something like:
```swift
let loadPath = try Ruby.getGlobalVar("$LOAD_PATH")
print(loadPath)
```

**Comment by xareelee** [comment]
Ok. It seems that I need to configure Ruby correctly. Thanks for your help.
